from src.utils.Base.BaseException import CustomBaseError


class ValidationError(CustomBaseError):
    pass
